apiVersion: v1
kind: Service
metadata:
  name: hungthp1-api
spec:
  selector:
    service: hungthp1-api
  ports:
  - name: "5050"
    protocol: TCP
    port: 5153
    targetPort: 5153

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hungthp1-api
  labels:
    service: hungthp1-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hungthp1-api
  template:
    metadata:
      labels:
        service: hungthp1-api
    spec:
      containers:
      - name: hungthp1-api
        image: 579273112224.dkr.ecr.us-east-1.amazonaws.com/udacitypr3:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
          - secretRef:
              name: passworkscrect
          - configMapRef:
              name: hungthp1config
      restartPolicy: Always
